# Generated by Django 5.1.2 on 2025-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ridehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=100)),
                ('seat_no', models.CharField(max_length=10)),
                ('travel_date', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
